/**
 * withLocalProperties
 *
 * `android/local.properties` を prebuild 時に自動生成する Expo config plugin。
 *
 * 解決する問題（学習事項 #5）:
 *   `expo prebuild --clean` 実行時に android/ 全体が再生成され、local.properties も削除される。
 *   再生成しないと `npx expo run:android` 等が `SDK location not found` で即失敗する。
 *
 * 動作:
 *   1. `withDangerousMod` で prebuild 後の android/ にアクセス
 *   2. ANDROID_HOME / ANDROID_SDK_ROOT / 既知の Windows デフォルトパス を順に探す
 *   3. `sdk.dir=<path>` の単一行で local.properties を上書き作成（冪等）
 *
 * SDK パス検出順序:
 *   1. process.env.ANDROID_HOME (setup_env.* で設定された値が最優先)
 *   2. process.env.ANDROID_SDK_ROOT (Android Studio 公式の新名称)
 *   3. C:\Users\<USER>\AppData\Local\Android\Sdk (Windows デフォルト)
 *   4. ~/Library/Android/sdk (macOS デフォルト、妻の Mac で iOS 開発時用)
 *   5. ~/Android/Sdk (Linux デフォルト、将来の CI)
 *
 * macOS/Linux でも安全に動く（プラットフォーム判定 + Windows 専用処理は無し）。
 * 既存 local.properties がある場合は完全上書き（差分マージはしない、シンプル優先）。
 *
 * 設計根拠: 02_設計/Windows ビルド設定の永続化方針.md v0.2 §1.4 mobile-engineer の便益軸
 *           + 作業ログ学習事項 #5
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');
const os = require('os');

/**
 * SDK パスを順番に探して最初に見つかったものを返す。
 * 全部見つからなければ null（プラグインは警告を出して何もしない）。
 */
function detectAndroidSdk() {
  const candidates = [
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    // Windows デフォルト
    process.platform === 'win32'
      ? path.join(os.homedir(), 'AppData', 'Local', 'Android', 'Sdk')
      : null,
    // macOS デフォルト
    process.platform === 'darwin'
      ? path.join(os.homedir(), 'Library', 'Android', 'sdk')
      : null,
    // Linux デフォルト
    process.platform === 'linux'
      ? path.join(os.homedir(), 'Android', 'Sdk')
      : null,
  ].filter(Boolean);

  for (const candidate of candidates) {
    try {
      if (fs.existsSync(candidate) && fs.statSync(candidate).isDirectory()) {
        return candidate;
      }
    } catch (_e) {
      // 権限不足等で失敗したら次の候補に進む
    }
  }
  return null;
}

/**
 * local.properties に書き出すコンテンツを生成。
 * Windows パスの \ をエスケープ（Java Properties 形式の慣習）。
 */
function buildLocalProperties(sdkPath) {
  const escapedPath = sdkPath.replace(/\\/g, '\\\\');
  return [
    '# Auto-generated by plugins/withLocalProperties.js',
    '# Do NOT edit manually — re-run `npx expo prebuild` to regenerate.',
    '# See 02_設計/Windows ビルド設定の永続化方針.md v0.2 + docs/environment_setup.md',
    `sdk.dir=${escapedPath}`,
    '',
  ].join('\n');
}

module.exports = function withLocalProperties(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const sdkPath = detectAndroidSdk();
      if (!sdkPath) {
        console.warn(
          '[withLocalProperties] Android SDK not found. ' +
            'Set ANDROID_HOME or install Android Studio. ' +
            'local.properties was NOT generated.',
        );
        return cfg;
      }

      const localPropertiesPath = path.join(
        cfg.modRequest.platformProjectRoot,
        'local.properties',
      );
      const content = buildLocalProperties(sdkPath);

      // 冪等性: 同内容ならスキップ、差分があれば上書き
      let shouldWrite = true;
      try {
        if (fs.existsSync(localPropertiesPath)) {
          const existing = fs.readFileSync(localPropertiesPath, 'utf8');
          if (existing === content) {
            shouldWrite = false;
          }
        }
      } catch (_e) {
        // 読み込み失敗時は上書きする
      }

      if (shouldWrite) {
        fs.writeFileSync(localPropertiesPath, content, 'utf8');
        console.log(
          `[withLocalProperties] android/local.properties written (sdk.dir=${sdkPath})`,
        );
      }

      return cfg;
    },
  ]);
};
